//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteWork.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoteWork.Resx.AppResource", typeof(AppResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        internal static string agimplaceholder {
            get {
                return ResourceManager.GetString("agimplaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulaşım İzni?.
        /// </summary>
        internal static string anasayfadisplayalert1 {
            get {
                return ResourceManager.GetString("anasayfadisplayalert1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rehberinize erişim izni gerekiyor....
        /// </summary>
        internal static string anasayfadisplayalert2 {
            get {
                return ResourceManager.GetString("anasayfadisplayalert2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzin Ver.
        /// </summary>
        internal static string anasayfadisplayalert3 {
            get {
                return ResourceManager.GetString("anasayfadisplayalert3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atla.
        /// </summary>
        internal static string anasayfadisplayalert4 {
            get {
                return ResourceManager.GetString("anasayfadisplayalert4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        internal static string aramasayfasiplaceholder {
            get {
                return ResourceManager.GetString("aramasayfasiplaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string ayarlartableroot {
            get {
                return ResourceManager.GetString("ayarlartableroot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HESAP AYARLARI.
        /// </summary>
        internal static string ayarlartablesection1 {
            get {
                return ResourceManager.GetString("ayarlartablesection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YARDIM.
        /// </summary>
        internal static string ayarlartablesection2 {
            get {
                return ResourceManager.GetString("ayarlartablesection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAKKINDA.
        /// </summary>
        internal static string ayarlartablesection3 {
            get {
                return ResourceManager.GetString("ayarlartablesection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Değiştir.
        /// </summary>
        internal static string ayarlartextcell1 {
            get {
                return ResourceManager.GetString("ayarlartextcell1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        internal static string ayarlartextcell10 {
            get {
                return ResourceManager.GetString("ayarlartextcell10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabımı Sil.
        /// </summary>
        internal static string ayarlartextcell2 {
            get {
                return ResourceManager.GetString("ayarlartextcell2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizlilik Tercihleri.
        /// </summary>
        internal static string ayarlartextcell3 {
            get {
                return ResourceManager.GetString("ayarlartextcell3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasıl Kullanılır?.
        /// </summary>
        internal static string ayarlartextcell4 {
            get {
                return ResourceManager.GetString("ayarlartextcell4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bize Yaz.
        /// </summary>
        internal static string ayarlartextcell5 {
            get {
                return ResourceManager.GetString("ayarlartextcell5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versiyon 1.0.
        /// </summary>
        internal static string ayarlartextcell6 {
            get {
                return ResourceManager.GetString("ayarlartextcell6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlkeler ve Koşullar.
        /// </summary>
        internal static string ayarlartextcell7 {
            get {
                return ResourceManager.GetString("ayarlartextcell7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizlilik ve Güvenlik.
        /// </summary>
        internal static string ayarlartextcell8 {
            get {
                return ResourceManager.GetString("ayarlartextcell8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadaşlarına Öner.
        /// </summary>
        internal static string ayarlartextcell9 {
            get {
                return ResourceManager.GetString("ayarlartextcell9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        internal static string entegrasyonplaceholder {
            get {
                return ResourceManager.GetString("entegrasyonplaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        internal static string girisyapbutoniptal {
            get {
                return ResourceManager.GetString("girisyapbutoniptal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dikkat.
        /// </summary>
        internal static string girisyapdisplayalert11 {
            get {
                return ResourceManager.GetString("girisyapdisplayalert11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen boşlukları doğru bir şekilde doldurunuz!.
        /// </summary>
        internal static string girisyapdisplayalert12 {
            get {
                return ResourceManager.GetString("girisyapdisplayalert12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        internal static string girisyapdisplayalert13 {
            get {
                return ResourceManager.GetString("girisyapdisplayalert13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dikkat.
        /// </summary>
        internal static string girisyapdisplayalert21 {
            get {
                return ResourceManager.GetString("girisyapdisplayalert21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgilerinizde eksik veya yanlış girdi tespit edilmiştir. Lütfen tekrar bilgilerinizi giriniz!.
        /// </summary>
        internal static string girisyapdisplayalert22 {
            get {
                return ResourceManager.GetString("girisyapdisplayalert22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        internal static string girisyapdisplayalert23 {
            get {
                return ResourceManager.GetString("girisyapdisplayalert23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Adresiniz.
        /// </summary>
        internal static string girisyaplabelmail {
            get {
                return ResourceManager.GetString("girisyaplabelmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz.
        /// </summary>
        internal static string girisyaplabelsifre {
            get {
                return ResourceManager.GetString("girisyaplabelsifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emin misin?.
        /// </summary>
        internal static string hesapsildisplayalert1 {
            get {
                return ResourceManager.GetString("hesapsildisplayalert1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabını silersen kayıtlı bütün ağını kaybedeceksin unutma!.
        /// </summary>
        internal static string hesapsildisplayalert2 {
            get {
                return ResourceManager.GetString("hesapsildisplayalert2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evet.
        /// </summary>
        internal static string hesapsildisplayalert3 {
            get {
                return ResourceManager.GetString("hesapsildisplayalert3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayır.
        /// </summary>
        internal static string hesapsildisplayalert4 {
            get {
                return ResourceManager.GetString("hesapsildisplayalert4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Adresiniz.
        /// </summary>
        internal static string hesapsillabel1 {
            get {
                return ResourceManager.GetString("hesapsillabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string hesapsillabel2 {
            get {
                return ResourceManager.GetString("hesapsillabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre(Tekrar).
        /// </summary>
        internal static string hesapsillabel3 {
            get {
                return ResourceManager.GetString("hesapsillabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        internal static string iptalbuton {
            get {
                return ResourceManager.GetString("iptalbuton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        internal static string kayitolabelad {
            get {
                return ResourceManager.GetString("kayitolabelad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Adresi.
        /// </summary>
        internal static string kayitolabelmailadresi {
            get {
                return ResourceManager.GetString("kayitolabelmailadresi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz.
        /// </summary>
        internal static string kayitolabelsifre {
            get {
                return ResourceManager.GetString("kayitolabelsifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz(Tekrar).
        /// </summary>
        internal static string kayitolabelsifretekrar {
            get {
                return ResourceManager.GetString("kayitolabelsifretekrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        internal static string kayitolabelsoyad {
            get {
                return ResourceManager.GetString("kayitolabelsoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        internal static string kayitolbutoniptal {
            get {
                return ResourceManager.GetString("kayitolbutoniptal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dikkat.
        /// </summary>
        internal static string kayitoldisplayalert11 {
            get {
                return ResourceManager.GetString("kayitoldisplayalert11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen boşlukları doldurunuz!.
        /// </summary>
        internal static string kayitoldisplayalert12 {
            get {
                return ResourceManager.GetString("kayitoldisplayalert12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        internal static string kayitoldisplayalert13 {
            get {
                return ResourceManager.GetString("kayitoldisplayalert13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dikkat.
        /// </summary>
        internal static string kayitoldisplayalert21 {
            get {
                return ResourceManager.GetString("kayitoldisplayalert21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen şifrenizi tekrar giriniz!.
        /// </summary>
        internal static string kayitoldisplayalert22 {
            get {
                return ResourceManager.GetString("kayitoldisplayalert22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        internal static string kayitoldisplayalert23 {
            get {
                return ResourceManager.GetString("kayitoldisplayalert23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dikkat.
        /// </summary>
        internal static string kayitoldisplayalert31 {
            get {
                return ResourceManager.GetString("kayitoldisplayalert31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgilerinizde eksik veya yanlış girdi tespit edilmiştir. Lütfen tekrar bilgilerinizi giriniz!.
        /// </summary>
        internal static string kayitoldisplayalert32 {
            get {
                return ResourceManager.GetString("kayitoldisplayalert32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        internal static string kayitoldisplayalert33 {
            get {
                return ResourceManager.GetString("kayitoldisplayalert33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadaşınızın kişisel bilgilerini ekleyin.
        /// </summary>
        internal static string kisiekle2label {
            get {
                return ResourceManager.GetString("kisiekle2label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        internal static string kisieklebuton {
            get {
                return ResourceManager.GetString("kisieklebuton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Arkadaşınızın temel bilgilerini ekleyin….
        /// </summary>
        internal static string kisieklelabel1 {
            get {
                return ResourceManager.GetString("kisieklelabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlk İzlenim.
        /// </summary>
        internal static string kisieklelabel10 {
            get {
                return ResourceManager.GetString("kisieklelabel10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayırt edici özelliği.
        /// </summary>
        internal static string kisieklelabel11 {
            get {
                return ResourceManager.GetString("kisieklelabel11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanışıklık.
        /// </summary>
        internal static string kisieklelabel12 {
            get {
                return ResourceManager.GetString("kisieklelabel12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çevre.
        /// </summary>
        internal static string kisieklelabel13 {
            get {
                return ResourceManager.GetString("kisieklelabel13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        internal static string kisieklelabel2 {
            get {
                return ResourceManager.GetString("kisieklelabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalıştığı Kurum.
        /// </summary>
        internal static string kisieklelabel3 {
            get {
                return ResourceManager.GetString("kisieklelabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Ünvanı.
        /// </summary>
        internal static string kisieklelabel4 {
            get {
                return ResourceManager.GetString("kisieklelabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaşadığı Şehir.
        /// </summary>
        internal static string kisieklelabel5 {
            get {
                return ResourceManager.GetString("kisieklelabel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon Numarası.
        /// </summary>
        internal static string kisieklelabel6 {
            get {
                return ResourceManager.GetString("kisieklelabel6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Adresi.
        /// </summary>
        internal static string kisieklelabel7 {
            get {
                return ResourceManager.GetString("kisieklelabel7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne zaman tanıştın.
        /// </summary>
        internal static string kisieklelabel8 {
            get {
                return ResourceManager.GetString("kisieklelabel8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nerede tanıştın.
        /// </summary>
        internal static string kisieklelabel9 {
            get {
                return ResourceManager.GetString("kisieklelabel9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        internal static string kisieklelabelsoyad {
            get {
                return ResourceManager.GetString("kisieklelabelsoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aile.
        /// </summary>
        internal static string kisieklepicker1 {
            get {
                return ResourceManager.GetString("kisieklepicker1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Arkadaşı.
        /// </summary>
        internal static string kisieklepicker2 {
            get {
                return ResourceManager.GetString("kisieklepicker2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okul Arkadaşı.
        /// </summary>
        internal static string kisieklepicker3 {
            get {
                return ResourceManager.GetString("kisieklepicker3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yakın Arkadaş.
        /// </summary>
        internal static string kisieklepicker4 {
            get {
                return ResourceManager.GetString("kisieklepicker4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer.
        /// </summary>
        internal static string kisieklepicker5 {
            get {
                return ResourceManager.GetString("kisieklepicker5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad.
        /// </summary>
        internal static string profilentitychildclassname1 {
            get {
                return ResourceManager.GetString("profilentitychildclassname1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temel.
        /// </summary>
        internal static string profilentitychildclassname10 {
            get {
                return ResourceManager.GetString("profilentitychildclassname10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        internal static string profilentitychildclassname11 {
            get {
                return ResourceManager.GetString("profilentitychildclassname11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş.
        /// </summary>
        internal static string profilentitychildclassname12 {
            get {
                return ResourceManager.GetString("profilentitychildclassname12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğitim.
        /// </summary>
        internal static string profilentitychildclassname13 {
            get {
                return ResourceManager.GetString("profilentitychildclassname13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eş ve çocuklarının isimleri.
        /// </summary>
        internal static string profilentitychildclassname14 {
            get {
                return ResourceManager.GetString("profilentitychildclassname14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ev adresin.
        /// </summary>
        internal static string profilentitychildclassname15 {
            get {
                return ResourceManager.GetString("profilentitychildclassname15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye olduğun dernek ve vakıflar.
        /// </summary>
        internal static string profilentitychildclassname16 {
            get {
                return ResourceManager.GetString("profilentitychildclassname16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlgilendiğin sporlar.
        /// </summary>
        internal static string profilentitychildclassname17 {
            get {
                return ResourceManager.GetString("profilentitychildclassname17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobilerin.
        /// </summary>
        internal static string profilentitychildclassname18 {
            get {
                return ResourceManager.GetString("profilentitychildclassname18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuttuğun takım.
        /// </summary>
        internal static string profilentitychildclassname19 {
            get {
                return ResourceManager.GetString("profilentitychildclassname19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyetin.
        /// </summary>
        internal static string profilentitychildclassname2 {
            get {
                return ResourceManager.GetString("profilentitychildclassname2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seyehatlerin.
        /// </summary>
        internal static string profilentitychildclassname20 {
            get {
                return ResourceManager.GetString("profilentitychildclassname20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaşadığın Şehir.
        /// </summary>
        internal static string profilentitychildclassname3 {
            get {
                return ResourceManager.GetString("profilentitychildclassname3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon Numaran.
        /// </summary>
        internal static string profilentitychildclassname4 {
            get {
                return ResourceManager.GetString("profilentitychildclassname4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Adresin.
        /// </summary>
        internal static string profilentitychildclassname5 {
            get {
                return ResourceManager.GetString("profilentitychildclassname5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to child21.
        /// </summary>
        internal static string profilentitychildclassname6 {
            get {
                return ResourceManager.GetString("profilentitychildclassname6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to child22.
        /// </summary>
        internal static string profilentitychildclassname7 {
            get {
                return ResourceManager.GetString("profilentitychildclassname7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to child23.
        /// </summary>
        internal static string profilentitychildclassname8 {
            get {
                return ResourceManager.GetString("profilentitychildclassname8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to child24.
        /// </summary>
        internal static string profilentitychildclassname9 {
            get {
                return ResourceManager.GetString("profilentitychildclassname9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad.
        /// </summary>
        internal static string profilentityclassname1 {
            get {
                return ResourceManager.GetString("profilentityclassname1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal Ağlar.
        /// </summary>
        internal static string profilentityclassname2 {
            get {
                return ResourceManager.GetString("profilentityclassname2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temel Bilgiler.
        /// </summary>
        internal static string profilentityclassname3 {
            get {
                return ResourceManager.GetString("profilentityclassname3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kişisel Bilgiler.
        /// </summary>
        internal static string profilentityclassname4 {
            get {
                return ResourceManager.GetString("profilentityclassname4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eski Şifre.
        /// </summary>
        internal static string sifredegistirlabel1 {
            get {
                return ResourceManager.GetString("sifredegistirlabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Şifre.
        /// </summary>
        internal static string sifredegistirlabel2 {
            get {
                return ResourceManager.GetString("sifredegistirlabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Şifre(Tekrar).
        /// </summary>
        internal static string sifredegistirlabel3 {
            get {
                return ResourceManager.GetString("sifredegistirlabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorun bildir / Soru sor / Öneri sun.
        /// </summary>
        internal static string sikayetlabeltext {
            get {
                return ResourceManager.GetString("sikayetlabeltext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        internal static string temelbilgibutoniptal {
            get {
                return ResourceManager.GetString("temelbilgibutoniptal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoteWork AŞ., Ruken Computer Ltd., vs..
        /// </summary>
        internal static string temelbilgidurumplaceholder {
            get {
                return ResourceManager.GetString("temelbilgidurumplaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temel bilgilerinizi hızlıca tamamlayın....
        /// </summary>
        internal static string temelbilgilabel1 {
            get {
                return ResourceManager.GetString("temelbilgilabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalıştığınız Kurum.
        /// </summary>
        internal static string temelbilgilabel2 {
            get {
                return ResourceManager.GetString("temelbilgilabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Unvanı.
        /// </summary>
        internal static string temelbilgilabel3 {
            get {
                return ResourceManager.GetString("temelbilgilabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üniversiteniz.
        /// </summary>
        internal static string temelbilgilabel4 {
            get {
                return ResourceManager.GetString("temelbilgilabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Çalışmıyorum).
        /// </summary>
        internal static string temelbilgiplaceholdercalismiyorum {
            get {
                return ResourceManager.GetString("temelbilgiplaceholdercalismiyorum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boğaziçi Üniversitesi, İstanbul Üniversitesi vs..
        /// </summary>
        internal static string temelbilgiuniversiteplaceholder {
            get {
                return ResourceManager.GetString("temelbilgiuniversiteplaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android Geliştirici, Doktor, Pazarlama Müdürü, vs..
        /// </summary>
        internal static string temelbilgiunvanplaceholder {
            get {
                return ResourceManager.GetString("temelbilgiunvanplaceholder", resourceCulture);
            }
        }
    }
}
